vim.api.nvim_create_user_command("CopyFileName", function()
	local filename = vim.fn.expand("%:t")
	vim.fn.setreg("+", filename)
	vim.notify('Copied "' .. filename .. '" to the clipboard!')
end, {})

vim.api.nvim_create_user_command("CopyAbsPath", function()
	local path = vim.fn.expand("%:p")
	vim.fn.setreg("+", path)
	vim.notify('Copied "' .. path .. '" to the clipboard!')
end, {})

vim.api.nvim_create_user_command("CopyRelPath", function()
	local path = vim.fn.fnamemodify(vim.fn.expand("%"), ":.")
	vim.fn.setreg("+", path)
	vim.notify('Copied "' .. path .. '" to the clipboard!')
end, {})
